GROK-12025:  Help | Development: update the Quality Assurance doc
datagrok-ai/public pull request #1626
Opened 2023-03-03 16:09 UTC by ahadzhanian

2023-03-03 16:28 UTC, dnillovna commented on help/develop/how-to/report-tickets.md
> +* **Assignee**. Assign Alexander Paramonov or Denis Kryvchuk if the issue
I think it is a good idea to add their nicknames or emails here

2023-03-08 14:01 UTC, skalkin commented on help/develop/admin/quality-assurance.md
> +* Docker Hub stores built artifacts, such as compiled code and packages, that
No comma needed before "that"

2023-03-08 14:16 UTC, skalkin requested changes
Looks great, but let's address my comments first; just merge it after that.

2023-03-08 14:16 UTC, skalkin commented on help/develop/admin/quality-assurance.md
> +
I think automated package tests are missing

2023-03-08 14:16 UTC, skalkin commented on help/develop/admin/quality-assurance.md
> +Is a tool within the Datagrok platform that provides a convenient interface for
We shouldn't start paragraphs with "Is a tool" or "It is the". I think it should be "Test Manager is a tool ..."

2023-03-08 14:16 UTC, skalkin commented on help/develop/admin/quality-assurance.md
> +designed to provide insights into how the Datagrok platform is utilized. Usage
Let's shorten the description, make it one sentence.

2023-03-08 14:16 UTC, skalkin commented on help/develop/how-to/report-tickets.md
> +This guide provides an easy set of rules for reporting issues and managing
Get rid of "easy", it's unnecessary and doesn't sound well, too (the author probably meant "simple") :)

2023-03-08 14:16 UTC, skalkin commented on help/develop/how-to/report-tickets.md
> +company do not differ in both issue tracking systems.
"are the same" would be better than "do not differ"

2023-03-08 14:16 UTC, skalkin commented on help/develop/how-to/report-tickets.md
> +* **Description**. Is important for testing and writing release notes. For an
Do not start sentences with "is". But continuing the sentence like that is ok:

**Description** is important

2023-03-13 09:39 UTC, merged