Dnahovskyi/grok 11749 new deploy documentation
datagrok-ai/public pull request #1735
Opened 2023-03-24 15:15 UTC by ksumag

выбрал коммиты по работе с документацией из ветки dnahovskyi/GROK-11749-Docs-Deploy-documentation

2023-04-17 12:50 UTC, dnillovna requested changes

2023-04-18 09:20 UTC, ksumag commented on help/develop/admin/deploy/configure-s3-backup.md
> +     ```
Yes, I did a mistake. I checked it out and find no {}

2023-04-19 18:28 UTC, dnillovna requested changes

2023-04-19 18:28 UTC, dnillovna commented on help/develop/admin/deploy/deploy-docker-swarm.md
> +   ```
Remove the part with "You can get token any time by typing in the manager node shell for workers:" it is a piece of extra information here. Lets keep it short and simple

2023-04-19 18:28 UTC, dnillovna commented on help/develop/admin/deploy/deploy-docker-swarm.md
> +## Prerequisites
Add to prerequisites that it requires 2 machines, one for datagrok and one for cvm. Also, specify the resources as in docker-compose instructions

2023-04-19 18:28 UTC, dnillovna commented on help/develop/admin/deploy/deploy-docker-swarm.md
> +2. Use the received token on worker nodes to join the swarm as described below. You can get
Not plural, single CVM node.

2023-04-19 18:28 UTC, dnillovna commented on help/develop/admin/deploy/deploy-docker-swarm.md
> +   ```
Useless information here, they will have only to machines, datagrok and cvm

2023-04-19 18:28 UTC, dnillovna commented on help/develop/admin/deploy/deploy-docker-swarm.md
> +3. From the manager node set labels to all nodes in the swarm cluster.
```suggestion
3. From the manager node (datagrok) set labels to all nodes in the swarm cluster.
```

2023-04-19 18:28 UTC, dnillovna commented on help/develop/admin/deploy/deploy-docker-swarm.md
> +   2. Add labels ```role==datagrok``` and ```role==cvm``` to nodes:
Add label role==datagrok to datagrok node which is the manager and role==cvm to CVM node which is the worker in the cluster

2023-04-19 18:28 UTC, dnillovna commented on docker/swarm.docker-compose.yaml
> +          "testTrackDbServer": "host.docker.internal",
Remove, it is not for clients

2023-04-19 18:28 UTC, dnillovna commented on docker/swarm.docker-compose.yaml
> +          "adminDevKey": "1111111111",
remove, they do not need a fixed devkey

2023-04-19 18:28 UTC, dnillovna commented on docker/swarm.docker-compose.yaml
> +          "testDevKey": "2222222222"
remove, they do not need a fixed devkey

2023-04-19 18:28 UTC, dnillovna commented on help/develop/admin/deploy/deploy-docker-swarm.md
> +`dbAdminLogin` and `dbAdminPassword` in `GROK_PARAMETERS`.
the predefined values are fine, remove the step from the how-to

2023-04-19 18:28 UTC, dnillovna commented on help/develop/admin/deploy/deploy-docker-swarm.md
> +   docker stack deploy -c ./swarm,docker-compose.yaml <STACK_NAME>
Specify the stack name `datagrok`, it will be fine for most clients, who so not want to think about details

2023-04-19 18:28 UTC, dnillovna commented on help/develop/admin/deploy/deploy-docker-swarm.md
> +        * CVM URL Client: `http://<CVM_VM_IP_ADDRESS>:8090`
This should be a DNS address, which will be accessed by client

2023-04-19 18:28 UTC, dnillovna commented on help/develop/admin/deploy/deploy.md
>  More information:
There should be "Next steps" with configuration for smtp and auth, which are important part of platform first-time deployment

2023-04-20 12:22 UTC, dnillovna commented on docker/swarm.docker-compose.yaml
> +      DOCKER_REGISTRY_PASS: "docker-registry-password"
It is better to remove, cause we do not mention registry in instructions. Or we need to add it.

2023-04-20 12:23 UTC, dnillovna commented on docker/swarm.docker-compose.yaml
> +          "createBetaUsers": true,
remove those also

2023-04-20 12:24 UTC, dnillovna commented on docker/swarm.docker-compose.yaml
> +    entrypoint: ./entrypoint.sh --main "jupyter kernelgateway --config=.jupyter/jupyter_kernel_gateway_config.py" --helper "gunicorn grok_helper:app --timeout 900 --chdir /home/grok/grok_helper -b 0.
Could you remove it? It is gonna change it is better for client just to use the value from Dockerfile

2023-04-20 12:25 UTC, dnillovna commented on docker/swarm.docker-compose.yaml
> +      - jkg_kernels:/home/grok/.local/share/jupyter/kernels/
We need it for dev cause we restart container every night, it is better to remove it for clients

2023-04-20 12:26 UTC, dnillovna commented on help/develop/admin/deploy/deploy-docker-swarm.md
> +2. From the manager node (datagrok) set labels to all nodes in the swarm cluster.
I think you lost the step where you added cvm as worker to the cluster

2023-04-21 13:11 UTC, dnillovna requested changes

2023-04-21 13:11 UTC, dnillovna commented on docker/swarm.docker-compose.yaml
> +  jkg_kernels:
leftovers

2023-04-21 13:11 UTC, dnillovna commented on docker/swarm.docker-compose.yaml
> +        - subnet: 192.168.2.0/24
We do not need to specify exact ipam, so it can be removed

2023-04-21 13:11 UTC, dnillovna commented on help/develop/admin/deploy/deploy-docker-swarm.md
> +      docker node update --label-add  role==cvm <cvm_node>
```suggestion
      docker node update --label-add  role==datagrok <datagrok_node_id>
      docker node update --label-add  role==cvm <cvm_node_id>
```

2023-04-21 13:11 UTC, dnillovna commented on help/develop/admin/deploy/deploy-docker-swarm.md
> +   1. List all nodes:
```suggestion
   1. List all nodes. We will need ids of the datagrok and CVM nodes for the next step:
```

2023-04-21 13:33 UTC, dnillovna approved these changes

2023-04-21 13:42 UTC, merged