GROK-12873: NGL viewer: Initial version of documentation
datagrok-ai/public pull request #1834
Opened 2023-04-24 15:57 UTC by GennadiyZakharov

Initial version of documentation for the NGL viewer component

2023-04-25 09:58 UTC, GennadiyZakharov commented
@lbankurova , the failed lint check came not form my changes. These are files added by somebody else in master. Should I fix it?

2023-04-25 15:01 UTC, lbankurova requested changes

2023-04-27 13:31 UTC, GennadiyZakharov commented on help/visualize/viewers/ngl.md
> +NglViewer is a Datagrok JsViewer
Fixed.

2023-04-27 14:26 UTC, GennadiyZakharov commented on help/visualize/viewers/ngl.md
> +Then you need to load the macromolecule file by using the "**Open...**"
Fixed.

2023-04-27 14:32 UTC, GennadiyZakharov commented on help/visualize/viewers/ngl.md
> +* Change the column with small molecules 3D structures via **Ligand** control.
Fixed

2023-04-27 14:33 UTC, GennadiyZakharov commented on help/visualize/viewers/ngl.md
> +* Change macromolecule representation mode via **Representation** control.
Fixed.

2023-04-27 14:34 UTC, GennadiyZakharov commented on help/visualize/viewers/ngl.md
> +| Move the atom to the viewer center | Click on the atom         |
Fixed

2023-04-27 14:52 UTC, GennadiyZakharov commented on help/visualize/viewers/ngl.md
> +**Note**: User interface for macromolecule loading from a file share
Fixed

2023-04-27 15:23 UTC, GennadiyZakharov commented on help/visualize/viewers/ngl.md
> +![NGL viewer](ngl-viewer.png)
Hist is non-animated image, so I used standard png image, as on the other help pages: 
https://datagrok.ai/help/visualize/viewers/box-plot

I created animated gif showing the representation options.

2023-05-02 16:06 UTC, skalkin commented
Images should be 800x500. Or even better, 1600x1000 (with the 2x magnification on non-retina screens)

2023-05-02 22:08 UTC, lbankurova approved these changes

2023-05-02 22:08 UTC, lbankurova commented on help/visualize/viewers/ngl.md
> +and **Style** info panes on the **Context Panel**.
Ok to merge but pls fix in master after you're done

2023-05-05 17:39 UTC, GennadiyZakharov commented on help/visualize/viewers/ngl.md
> +## Interaction with other viewers
Fixed

2023-05-10 08:33 UTC, GennadiyZakharov commented on help/visualize/viewers/ngl.md
> +![NGL viewer](ngl-viewer.png)
Aimated GIFs created.

2023-05-10 08:34 UTC, merged