GROK-11511: Help: Added separate article
datagrok-ai/public pull request #2409
Opened 2023-10-16 17:51 UTC by PavloPolovyi

2023-10-16 20:54 UTC, skalkin requested changes
Not bad, but needs improvements.

2023-10-16 20:54 UTC, skalkin commented on help/develop/function_results_cache.md
> +>Note: Additionally you can toggle **Cache Schema**: to speed up building the database schema.
Too many unnecessary words. Simplify the message. And describe the downside.

2023-10-16 20:54 UTC, skalkin commented on help/develop/function_results_cache.md
> +Datagrok can cache the results of functions on both client and server sides.
What I liked about the previous version is that it listed the benefits ("to improve query performance.")

2023-10-16 20:54 UTC, skalkin commented on help/develop/function_results_cache.md
> +Datagrok can cache the results of functions on both client and server sides.
Also you have to expand here on what functions are (queries/computations/et), why caching might be a good idea (to improve responsiveness, reduce traffic, etc), and what are good candidates for caching (immutable, long-running functions producing not huge results that people execute over and over with the same parameters).

2023-10-16 20:54 UTC, skalkin commented on help/develop/function_results_cache.md
> +![How to apply cache for connection](./apply-connection-cache.gif "Apply cache")
No need for an animated gif here (also huge! size should be 800x500 for animated gifs). A small static image will suffice.

2023-10-16 20:54 UTC, skalkin commented on help/develop/function_results_cache.md
> +* Function output parameters should be scalar (integer, float or string) or of the following types - [dataframe](../datagrok/concepts/table.md), [graphics or datetime](../datagrok/concepts/functions/
you forgot date parameter

2023-10-16 20:54 UTC, skalkin commented on help/develop/function_results_cache.md
> +* Maximum cache size for the function is 100 MB.
This is not clear.

2023-10-16 20:54 UTC, skalkin commented on help/develop/function_results_cache.md
> +### To enable Client-side cache
Don't call sections "To ..."

2023-10-16 20:54 UTC, skalkin commented on help/develop/function_results_cache.md
> +2. Toggle **Client-side cache** switch.
Not "toggle" but "Check".

2023-10-16 20:54 UTC, skalkin commented on help/develop/function_results_cache.md
> +You can apply cache to almost all types of functions. But it really shines with [DataQueries](../access/access.md#data-query) and [Scripts](../compute/scripting.md).
What is "apply cache"? I think "cache results" sounds a lot better

2023-10-16 20:54 UTC, skalkin commented on help/develop/function_results_cache.md
> +2. Optionally add `meta.cache.invalidateOn` to specify when the cache is invalidated. This parameter accepts valid cron expressions. If not specified, the cache will never be updated.
Previous version had a link to what "cron expressions" are

2023-10-16 20:54 UTC, skalkin commented on help/develop/function_results_cache.md
> +Only those functions that have one or more output parameters can be cached.
This is not necessary. If you say that Datagrok caches results, then it's clear that if a function has no results, it won't be cached.

2023-10-16 20:54 UTC, skalkin commented on help/develop/function_results_cache.md
> +Datagrok stores the results of functions in a relational database as server-side caching. It doesn't have any limitations on size or type of parameters
> in a relational database

This is unnecessary information, and it's also incomplete. Cut it.

2023-10-16 20:54 UTC, skalkin commented on help/develop/function_results_cache.md
> +and will be used when **Client-side cache** is not suitable.
> and will be used when **Client-side cache** is not suitable.

This is wrong! Both caches complement each other.

2023-10-16 20:54 UTC, skalkin commented on help/develop/function_results_cache.md
> +### To enable Server-side cache
This should not be a header

2023-10-17 07:51 UTC, PavloPolovyi commented on help/develop/function_results_cache.md
> +* Function output parameters should be scalar (integer, float or string) or of the following types - [dataframe](../datagrok/concepts/table.md), [graphics or datetime](../datagrok/concepts/functions/
I mentioned it 

> [graphics or datetime]

2023-10-21 19:00 UTC, skalkin approved these changes
Nice!

Just one more thing - next time please answer my comments (a quick "fixed" or "done" or "addressed" is enough), otherwise I have to both recall the context and then check if you fixed it, which is very unproductive. A quick "fixed" saves me a lot of time and effort.

2023-10-22 15:26 UTC, merged