GROK-13661: Scripting documentation improve
datagrok-ai/public pull request #2610
Opened 2023-12-25 14:23 UTC by GennadiyZakharov

- Column selectors
- FileIO
- Converting script to application

2024-01-08 14:50 UTC, skalkin requested changes
Looks good to me, just some minor comments.

2024-01-08 14:50 UTC, skalkin commented on help/compute/scripting-for-non-developers.mdx
> +When you run this script, Datagrok will return to you the `FileInfo` object in the scalar variables panel.
"to you" is not needed

2024-01-09 10:05 UTC, GennadiyZakharov commented on help/compute/scripting-for-non-developers.mdx
> +Let's modify the default example accept and return both dataframes and scalars.
Fixed

2024-01-09 10:08 UTC, GennadiyZakharov commented on help/compute/scripting-for-non-developers.mdx
> +Datagrok automatically catches and opens the new dataframe.
Agree. Fixed.

2024-01-09 10:10 UTC, GennadiyZakharov commented on help/compute/scripting-for-non-developers.mdx
> +  In the script it will be a string variable containing column ID
Fixed.

2024-01-09 10:16 UTC, GennadiyZakharov commented on help/compute/scripting-for-non-developers.mdx
> +When you run this script, Datagrok will return to you the `FileInfo` object in the scalar variables panel.
Fixed.

2024-01-09 10:45 UTC, GennadiyZakharov commented on help/compute/scripting-for-non-developers.mdx
> +Both of these selectors require at least one **Dataframe** input
I reworked it - I hope now it's better.

2024-01-12 17:10 UTC, mistressxalexis reviewed
contextual information

2024-01-12 17:12 UTC, mistressxalexis approved these changes

2024-01-15 10:23 UTC, merged