Custom ML Functions
datagrok-ai/public pull request #88
Opened 2021-08-26 00:14 UTC by GitDenisGostev

2021-08-28 17:19 UTC, alex-aprm approved these changes

2021-08-28 17:20 UTC, alex-aprm commented
@konstantin-doncov what do you think?

2021-08-31 14:06 UTC, konstantin-doncov commented on packages/CustomML/src/package.js
> +}
Better to remove this test function

2021-08-31 14:07 UTC, konstantin-doncov requested changes
Please remove the test function

2021-09-01 00:45 UTC, Denomet commented on packages/CustomML/src/package.js
> +}
Removed test function from package.js

2021-09-01 06:32 UTC, merged